project_id = "jukdsypvuehnniskgpfd"

[functions.register-demo-company]
verify_jwt = false

[functions.geocode-company-address]
verify_jwt = false

[functions.gocardless-payments]
verify_jwt = true

[functions.download-signed-repair-order]
verify_jwt = true

[functions.send-payment-reminder-webhook]
verify_jwt = false

[functions.analyze-driving-license]
verify_jwt = true

[functions.analyze-violation]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.get-active-repair-orders]
verify_jwt = true

[functions.send-token-alert]
verify_jwt = true

[functions.get-user-context]
verify_jwt = false

[functions.generate-iframe-token]
verify_jwt = true

[functions.send-documents-request-email]
verify_jwt = false

[functions.notify-company-documents-complete]
verify_jwt = false

[functions.download-signed-contract]
verify_jwt = true

[functions.send-cession-registered-mail]
verify_jwt = true

[functions.process-documents-request]
verify_jwt = false

[functions.auto-assign-next-task]
verify_jwt = false

[functions.insert-emergency-with-priority]
verify_jwt = false

[functions.vehicle-status-monitor]
verify_jwt = false

[functions.task-started-webhook]
verify_jwt = false

[functions.n8n-response-handler]
verify_jwt = false

[functions.insee-sirene]
verify_jwt = false