project_id = "jukdsypvuehnniskgpfd"

[functions.update-user]
verify_jwt = true

[functions.get-active-repair-orders]
verify_jwt = true

[functions.send-token-alert]
verify_jwt = true

[functions.get-user-context]
verify_jwt = false

[functions.generate-iframe-token]
verify_jwt = true