// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyujmjdkcftjoadytlao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5dWptamRrY2Z0am9hZHl0bGFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDgxMjgsImV4cCI6MjA2MzMyNDEyOH0.b1ukmYwzT5kQ4WfYVcZ6YKloULCULyM-kf8uzpefIB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);