
// This file is automatically generated. Do not edit it directly.
// Modified to use static data for demo purposes
import { mockSupabaseClient } from '@/data/mockSupabaseClient';
import type { Database } from './types';

// For demo/screenshot purposes, we use a mock client with static data
// Original code kept for reference:
/*
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jukdsypvuehnniskgpfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1a2RzeXB2dWVobm5pc2tncGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTA5MTIsImV4cCI6MjA2MzU2NjkxMn0.fJcqL0Sg_x7AXacC6lhqic-VWhvI46D3tFgRcpgchxo";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    }
  }
);
*/

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = mockSupabaseClient as any;
